### ISSUE TITLE
RuntimeError: A QApplication instance already exists.

### ISSUE THREAD

**Issue by msabramo** [spulec/zester#1]
I was trying to create a `tox.ini` for [tox](http://tox.testrun.org/latest/) for this project (I [already created a working `tox.ini` for Ghost.py](https://github.com/jeanphix/Ghost.py/pull/20)) but I'm getting this weird error. Any ideas? (I'm not too familiar with PyQt, PySide, etc.)

```
marca@ubuntu:~/dev/git-repos/zester$ tox
GLOB sdist-make: /home/marca/dev/git-repos/zester/setup.py
py27 sdist-reinst: /home/marca/dev/git-repos/zester/.tox/dist/zester-0.0.3.zip
py27 runtests: commands[0]

(python2.7:10617): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(python2.7:10617): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(python2.7:10617): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(python2.7:10617): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
.EException AttributeError: "'Ghost' object has no attribute 'app'" in <bound method Ghost.__del__ of <ghost.ghost.Ghost object at 0xa7ebd2c>> ignored

======================================================================
ERROR: test_single_client (test_zester.ZesterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marca/dev/git-repos/zester/tests/test_zester.py", line 34, in test_single_client
    url=weather_snapshot)
  File "/home/marca/dev/git-repos/zester/tests/fixtures/weather_client.py", line 13, in __init__
    super(WeatherClient, self).__init__(*args, **kwargs)
  File "/home/marca/dev/git-repos/zester/zester/client.py", line 15, in __init__
    self._ghost = Ghost()
  File "/home/marca/dev/git-repos/zester/.tox/py27/local/lib/python2.7/site-packages/ghost/ghost.py", line 184, in __init__
    self.app = QApplication(['ghost'])
RuntimeError: A QApplication instance already exists.

----------------------------------------------------------------------
Ran 2 tests in 7.581s

FAILED (errors=1)
ERROR: InvocationError: '/home/marca/dev/git-repos/zester/.tox/py27/bin/nosetests'
__________________________________________________________________ summary __________________________________________________________________
ERROR:   py27: commands failed
```

**Comment by spulec** [comment]
Hi Marc,

The tests need to be run with the HEAD of ghost.py. There were some changes since the last stable release of it.

Sorry that this is not documented; I'm not exactly sure where to put in. I suppose I could add a section about the tests to the readme.
